-- Employee_Table
CREATE TABLE Employee_Table (
    EMP_ID INT PRIMARY KEY,
    EMP_CODE VARCHAR(225),
    FULL_NAME VARCHAR(225),
    GENDER VARCHAR(8),
    DATE_OF_BIRTH DATE,
    DESIGNATION VARCHAR(225),
    JOINING_DATE DATE,
    SALARY INT,
    DEPT_ID INT,
    NATIONALITY VARCHAR(225)
);

-- Department_Table
CREATE TABLE Department_Table (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(225),
    DEPT_HEAD_ID INT,
    FOREIGN KEY (DEPT_ID)
        REFERENCES Employee_Table (EMP_ID)
        ON DELETE CASCADE,
    FOREIGN KEY (DEPT_HEAD_ID)
        REFERENCES Employee_Table (EMP_ID)
        ON DELETE SET NULL
);