WITH GENDER_COUNT AS(
    SELECT DEPT_ID,
    SUM( CASE WHEN GENDER= 'MALE' THEN 1 ELSE 0 END) MALE_COUNT,
    SUM( CASE WHEN GENDER='FEMALE' THEN 1 ELSE 0 END) FEMALE_COUNT
    FROM Employee_Table
    GROUP BY DEPT_ID
)
SELECT DEPT_ID
FROM GENDER_COUNT
WHERE MALE_COUNT>FEMALE_COUNT;
